#!/bin/bash

##############################################################
# AUTHOR:
# Justin Silver
#
# DESCRIPTION: 
# Script to download a random IC die image from the internet
# and set it as the computer background. Currently only
# sourcing from zeptobars.
#
# ACKNOWLEDGEMENTS:
# Thanks to https://zeptobars.com/en/ for the amazing images
#############################################################

# constants
ZEPTO_URL="https://zeptobars.com/en/"
PREFIX_IMAGE_URL="https://s.zeptobars.com/"
IMAGE_TYPE=".jpg"
BG_PATH="$HOME/bg" # background directory on machine (needs to have write access)

if [[ ! -d $BG_PATH ]]; then
    mkdir "$BG_PATH"
fi

# clean-up from last download 
# feel free to comment this out if you want to keep the downloaded images
rm -f $BG_PATH/*$IMAGE_TYPE*

# get total number of pages (from home page)
max_num_pages=\
$(
    # raw HTML
    wget --quiet $ZEPTO_URL --output-document=- | \
    # extract displayed page numbers (probably a better way to do this...)
    grep --only-matching --extended-regexp 'href="\?p=[0-9]+"' | \
    # separate number
    cut --delimiter='=' --fields=3 | \
    cut --delimiter='"' --fields=1 | \
    sort --numeric-sort | \
    tail -1 
) 

# random page select from total number of pages (1 inclusive)
page_idx=$((1 + $RANDOM % $max_num_pages))

# get one of the images from page_idx
image_url=\
$(
    # raw HTML
    wget --quiet "$ZEPTO_URL?p=$page_idx" --output-document=- | \
    # extract img links
    grep --only-matching --extended-regexp 'src="https://([^"#?]+)"' | \
    # remove HTML
    cut --delimiter='"' --fields=2 | \
    # randomize extracted img link
    shuf --head-count=1
)

# download img
wget --quiet --directory-prefix="$BG_PATH/" $image_url

# set as background image
image_file=${image_url#$PREFIX_IMAGE_URL}

# some images look better with "scaled", some  with "wallpaper"
# perhaps add some conditional setting depending on image resolution 
gsettings set org.gnome.desktop.background picture-options "scaled"
gsettings set org.gnome.desktop.background picture-uri "file:///$BG_PATH/$image_file"

# tell user about the awesome new IC background
ic_name=${image_file%%.*} # remove file type
zenity --question --title "Hello $(whoami) !" \
--text "Your IC of the day is: <b>$ic_name</b>\n\n<sub><i>Image source:\n$image_url</i></sub>" \
--window-icon='info' \
--ok-label "Google this IC" --cancel-label="Close" \
--width=420 --height=100

# check return code
if [[ $? -eq 0 ]]; then
    # open up default browser and search for ic_name
    xdg-open "https://www.google.com/search?q=$ic_name" &>/dev/null &
fi

